"""Remove role column from profiles table final

Revision ID: 28a1d79bdb7c
Revises: 8c6999f237ca
Create Date: 2025-11-23 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28a1d79bdb7c"
down_revision: Union[str, None] = "8c6999f237ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("role", sa.String(), nullable=True, default="customer")
    )
    # ### end Alembic commands ###
