"""Remove role column from profiles table

Revision ID: 348557d9877a
Revises: 4888e05a05a0
Create Date: 2025-11-16 22:07:53.320257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348557d9877a'
down_revision: Union[str, None] = '4888e05a05a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
