"""Add role column back to profiles table for Supabase compatibility

Revision ID: 8c6999f237ca
Revises: f36b0e9c409f
Create Date: 2025-11-16 22:41:00.654502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c6999f237ca"
down_revision: Union[str, None] = "f36b0e9c409f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("role", sa.String(), nullable=True, default="customer")
    )
    op.alter_column(
        "user_role_links",
        "role_name",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("CUSTOMER", "RECEPTIONIST", "TECHNICIAN", "ADMIN", name="role"),
        existing_nullable=False,
        postgresql_using="role_name::role",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_role_links",
        "role_name",
        existing_type=sa.Enum(
            "CUSTOMER", "RECEPTIONIST", "TECHNICIAN", "ADMIN", name="role"
        ),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("profiles", "role")
    # ### end Alembic commands ###
