"""refactor_user_role_link_pk_definition

Revision ID: f0e4886da080
Revises: 28a1d79bdb7c
Create Date: 2025-11-23 23:00:54.554188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e4886da080'
down_revision: Union[str, None] = '28a1d79bdb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
